config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
      controllers: {
        sessions: 'admins/sessions',
        passwords: 'admins/passwords',
        registrations: 'admins/registrations',
  }

	namespace :admins do
    get 'home/about'
    resources :contacts
	end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'home#top'
  post 'users/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'users/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  get "user/follow/:id" => "users/users#follow", as:'user_follow'
  get "user/followed:id" => "users/users#followed", as:'user_followed'
  get 'food_comment/new'
  get '/search' => 'search#search', as: 'search'

  namespace :users do
    get 'users/userallpost'
    get 'users/favolist'

    resources :users
    resources :contacts
  	resources :foods do
      resource :food_favorites, only: [:create, :destroy]
      resources :food_comments, only: [:create, :destroy]
    end
    resources :nonfoods do
      resource :nonfood_favorites, only: [:create, :destroy]
      resources :nonfood_comments, only: [:create, :destroy]
    end
  end

end

app/models/nonfood.rb
class Nonfood < ApplicationRecord
  belongs_to :user
  has_many :nonfood_comments, dependent: :destroy
  has_many :nonfood_comment_users, through: :nonfood_comments, source: 'user'
  has_many :nonfood_favorites, dependent: :destroy

  attachment :nonfood_image
  acts_as_taggable

  validates :nonfood_name, presence: true
  validates :nonfood_introduction, presence: true, length: { maximum: 300 }

  def nonfood_favorited_by?(user)
    nonfood_favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :foods, dependent: :destroy
  has_many :nonfoods, dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :nonfood_comments, dependent: :destroy
  has_many :food_favorites, dependent: :destroy
  has_many :nonfood_favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォロー取得 # rubocop:disable Rails/InverseOf
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy # フォロワー取得 # rubocop:disable Rails/InverseOf
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :contact, dependent: :destroy
  attachment :user_image

  enum profession: { profession_private: 0, unemployed: 1, worker: 2, housework: 3 }
  enum gender: { gender_private: 0, man: 1, human: 2 }
  enum age_group: { age_private: 0, Twenties: 1, thirties: 2, forties: 3,
                    fifties: 4, sixties: 5, seventies: 6, eighties: 7, nineties: 8 }
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      redirect_to root_path
    else
      @contacts = Contact.all
      @users = User.all
      render :new
    end
      flash[:success] = 'お問い合わせを送信しました。'
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :body, :reply)
  end
end

app/controllers/users/food_comments_controller.rb
class Users::FoodCommentsController < ApplicationController
  def create
    @food = Food.find(params[:food_id])
    @foodnew = Food.new
    @food_comment = current_user.food_comments.new(food_comment_params)
    @food_comment.food_id = @food.id
    @food_comment.save
  end

  def destroy
    FoodComment.find_by(id: params[:id], food_id: params[:food_id]).destroy
    @food = Food.find(params[:food_id])
    @food_comments = @food.food_comments
  end

  private

  def food_comment_params
    params.require(:food_comment).permit(:food_comment)
  end
end

app/controllers/users/food_favorites_controller.rb
class Users::FoodFavoritesController < ApplicationController
  before_action :food_params

  def create
    food_favorite = @food.food_favorites.new(user_id: current_user.id)
    food_favorite.save
  end

  def destroy
    food_favorite = current_user.food_favorites.find_by(food_id: @food.id)
    food_favorite.destroy
  end

  private

  def food_params
    @food = Food.find(params[:food_id])
  end
end

app/controllers/users/foods_controller.rb
class Users::FoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update destroy new create]

  def new
    @user = current_user
    @food_new = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to users_food_path(@food)
    else
      @user = current_user
      @food_new = Food.new
      render 'new'
    end
  end

  def index
    @foods = Food.page(params[:page]).reverse_order
    @user = current_user
    @foodall_ranks = Food.find(FoodFavorite.group(:food_id).order('count(food_id) desc').limit(3).pluck(:food_id))
  end

  def show
    @food = Food.find(params[:id])
    @user = @food.user
    @food_comment = FoodComment.new
    @food_comments = @food.food_comments
  end

  def edit
    @user = current_user
    @food = Food.find(params[:id])
    redirect_to users_foods_path if @food.user != current_user
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to users_food_path(@food.id)
    else
      render 'edit'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to users_foods_path
  end

  private

  def food_params
    params.require(:food).permit(
      :food_image,
      :food_name,
      :food_introduction,
      :tag_list)
  end
end

app/controllers/users/nonfood_comments_controller.rb
class Users::NonfoodCommentsController < ApplicationController
  def create
    @nonfood = Nonfood.find(params[:nonfood_id])
    @nonfoodnew = Nonfood.new
    @nonfood_comment = current_user.nonfood_comments.new(nonfood_comment_params)
    @nonfood_comment.nonfood_id = @nonfood.id
    @nonfood_comment.save
  end

  def destroy
    NonfoodComment.find_by(id: params[:id], nonfood_id: params[:nonfood_id]).destroy
    @nonfood = Nonfood.find(params[:nonfood_id])
    @nonfood_comments = @nonfood.nonfood_comments
  end

  private

  def nonfood_comment_params
    params.require(:nonfood_comment).permit(:nonfood_comment)
  end
end

app/controllers/users/nonfood_favorites_controller.rb
class Users::NonfoodFavoritesController < ApplicationController
  before_action :nonfood_params

  def create
    nonfood_favorite = @nonfood.nonfood_favorites.new(user_id: current_user.id)
    nonfood_favorite.save
  end

  def destroy
    nonfood_favorite = current_user.nonfood_favorites.find_by(nonfood_id: @nonfood.id)
    nonfood_favorite.destroy
  end

  private

  def nonfood_params
    @nonfood = Nonfood.find(params[:nonfood_id])
  end
end

app/controllers/users/nonfoods_controller.rb
class Users::NonfoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update destroy new create]

  def new
    @user = current_user
    @nonfood_new = Nonfood.new
  end

  def create
    @nonfood = Nonfood.new(nonfood_params)
    @nonfood.user = current_user
    if @nonfood.save
      redirect_to users_nonfood_path(@nonfood)
    else
      @user = current_user
      @nonfood_new = Nonfood.new
      render 'new'
    end
  end

  def index
    @nonfoods = Nonfood.page(params[:page]).reverse_order
    @user = current_user
    @nonfoodall_ranks = Nonfood.find(NonfoodFavorite
      .group(:nonfood_id)
      .order('count(nonfood_id) desc')
      .limit(3).pluck(:nonfood_id))
  end

  def show
    @nonfood = Nonfood.find(params[:id])
    @user = @nonfood.user
    @nonfood_comment = NonfoodComment.new
    @nonfood_comments = @nonfood.nonfood_comments
  end

  def edit
    @user = current_user
    @nonfood = Nonfood.find(params[:id])
    redirect_to users_nonfoods_path if @nonfood.user != current_user
  end

  def update
    @nonfood = Nonfood.find(params[:id])
    if @nonfood.update(nonfood_params)
      redirect_to users_nonfood_path(@nonfood.id)
    else
      render 'edit'
    end
  end

  def destroy
    @nonfood = Nonfood.find(params[:id])
    @nonfood.destroy
    redirect_to users_nonfoods_path
  end

  private

  def nonfood_params
    params.require(:nonfood).permit(
      :nonfood_image,
      :nonfood_name,
      :nonfood_introduction,
      :tag_list)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to users_user_path(current_user) if @user != current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_user_path(@user.id)
    else
      render action: :edit
    end
  end

  def follow
    @user = User.find(params[:id])
  end

  def followed
    @user = User.find(params[:id])
    @users = User.all
  end

  def userallpost # rubocop:disable Metrics/AbcSize
    @user = current_user
    @foods = current_user.foods.all.reverse_order
    @nonfoods = current_user.nonfoods.all.reverse_order
    @instances = @foods | @nonfoods # それぞれの複数インスタンスを合算して、一つの配列として出す
    @instances.sort! { |a, b| b[:created_at] <=> a[:created_at] } # 作成降順に並び替え
    @instances = Kaminari.paginate_array(@instances).page(params[:page]) # paginate_arrayでカミナリに対応した記述変換
  end

  def favolist
    @user = current_user
    @foods = Food.all.reverse_order
    @nonfoods = Nonfood.all.reverse_order
    @instances = @foods | @nonfoods
    @instances.sort! { |a, b| b[:created_at] <=> a[:created_at] }
    @instances = Kaminari.paginate_array(@instances).page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(
      :name, 
      :user_image, 
      :user_introduction, 
      :profession, 
      :gender, 
      :age_group)
  end
end

app/helpers/users/contacts_helper.rb
module Users::ContactsHelper
end

app/helpers/users/food_comments_helper.rb
module Users::FoodCommentsHelper
end

app/helpers/users/food_favorites_helper.rb
module Users::FoodFavoritesHelper
end

app/helpers/users/foods_helper.rb
module Users::FoodsHelper
end

app/views/users/nonfoods/_nonfood.html.erb
<% if current_user.present? %>
  <% if nonfood.nonfood_favorited_by?(current_user) %>
    <%= link_to users_nonfood_nonfood_favorites_path(nonfood), method: :delete, remote: true do %>
      <div class = "iine__button">♡️<%= nonfood.nonfood_favorites.count %></div>
    <% end %>
  <% else %>
    <%= link_to users_nonfood_nonfood_favorites_path(nonfood), method: :post, remote: true do %>
      <div class = "iine__button">♡️<%= nonfood.nonfood_favorites.count %></div>
    <% end %>
  <% end %>
<% else %>
  <div class = "iine__button">♡️<%= nonfood.nonfood_favorites.count %></div>
<% end %>

app/views/users/nonfoods/edit.html.erb
<div class="container">
 <h2>雑貨品編集ページ</h2>
 <%= render 'layouts/error_messages', resource: @nonfood %>
  <div class="row">
	<div class="col-md-5">
	  <%= form_for(@nonfood, url: users_nonfood_path ) do |f| %>
		<div class="nonfoodpost__image"><%= f.label :nonfood_image, "雑貨品イメージ画像" %>
		  <%= attachment_image_tag @nonfood, :nonfood_image, format: "jpeg", id: "img_prev", fallback: "no_image.jpg" %>
		  <br>
		 	画像選択<%= f.attachment_field :nonfood_image %></div>
		<div><%= f.label :nonfood_name, "アイデア名（雑貨品）" %><br>
             <%= f.text_field :nonfood_name, :size=>"60" %>
        </div>
	    <div><%= f.label :nonfood, :タグ %><br>
			 <%= f.text_field :tag_list, value: @nonfood.tag_list.join(','), :size=>"60" %>
		</div>
	    <div><%= f.label :nonfood_introduction, "商品説明(用途・形・お値段等)" %><br>
	         <%= f.text_area :nonfood_introduction, :size=>"60x11" %>
	    </div>
		<div>
		  <%= f.submit('保存する',class: 'btn btn-info my-1 mb-5 px-5') %>
		</div>
	  <% end %>
	</div>
  </div>
</div>

<script>
$(document).on("turbolinks:load", function(){
  function readURL(input) {
    if(input.files && input.files[0]){
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.nonfood_image').attr('src', e.target.result);　//取得したurlにアップロード画像のurlを挿入
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  														  // inputのidから情報の取得
  $("#nonfood_nonfood_image").change(function(){
    readURL(this);
  });
});
</script>

app/views/users/nonfoods/index.html.erb
<div class="container">
  <div class="row">
    <h1 style="text-align: center;">雑貨品アイデア投稿</h1>
      <% if flash[:error].present? %>
        <ul class="errors">
          <% flash[:error].each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>
    <h2 style="padding-left: 30px; ">雑貨品アイデアTOP３(いいね編)</h2>
      <!-- ランキングTOP３  -->
      <% @nonfoodall_ranks.each.with_index(1) do |nonfoodall_rank,i| %>
        <div class="card" >
          <div class="card-img-top ranking__cards"><%= link_to users_nonfood_path(nonfoodall_rank) do %>
            <%= attachment_image_tag nonfoodall_rank, :nonfood_image, format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
          <p><%="#{i}位"%></p>
          </div>
          <div class="card-body">
            <h4 class="card-title"><%= link_to users_nonfood_path(nonfoodall_rank) do %>
              <%= nonfoodall_rank.nonfood_name %>
            <% end %></h4>
            <p class="card-text">
              <%= link_to nonfoodall_rank.user.name, users_user_path(nonfoodall_rank.user) %></p>
            <div style="padding-bottom: 5px">
              <span class="badge badge-secondary" >
                <%= nonfoodall_rank.tag_list %></span>
                <%= nonfoodall_rank.nonfood_comments.count %>件コメント
            </div>
            <!-- いいね表示ここから -->
            <div>
              <span class="nonfood_<%= nonfoodall_rank.id %>" style="display: block; text-align: left;">
                <%= render 'nonfood', nonfood: nonfoodall_rank %>
              </span>
            </div>
            <!-- いいね表示ここからまで -->
            <div><p class="text-right">
              <%= l nonfoodall_rank.created_at, format: :short %></p>
            </div>
          </div>
        </div>
      <% end %>
      <!-- ランキングここまで -->
      <br><br><br><br>
      <!-- 一覧投稿 -->
      <h2 style="padding-left: 30px; ">みんなの雑貨品アイデア投稿</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>アイデア画像</th>
            <th>アイデア名</th>
            <th>ジャンル</th>
            <th>投稿者名</th>
            <th>投稿日時</th>
            <th>いいね</th>
          </tr>
        </thead>
        <tbody>
          <% @nonfoods.each do |nonfood|%>
            <tr>
              <td class="nonfoodtd1 nonfood__picture"><%= link_to users_nonfood_path(nonfood) do %>
                <%= attachment_image_tag nonfood, :nonfood_image, format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %></td>
              <td class="nonfoodtd1"><%= link_to users_nonfood_path(nonfood) do %>
                <%= nonfood.nonfood_name %>
              <% end %></td>
              <td><span class="badge badge-secondary">
                <%= nonfood.tag_list %></span></td>
              <td class="nonfoodtd1">
                <%= link_to nonfood.user.name, users_user_path(nonfood.user) %></td>
              <td><%= l nonfood.created_at, format: :short %></td>
              <td class="nonfoodtd1">
                <div>
                  <span class="nonfood_<%= nonfood.id %>" style="display: block; text-align: left;">
                    <%= render 'nonfood', nonfood: nonfood %>
                  </span>
                </div>
              </td>
           </tr>
        　<% end %>
        </tbody>
      </table>
      <!-- 一覧ここまで -->
   <span style="display: block; text-align: center;"><%= paginate @nonfoods %></span>
  </div>
</div>

app/views/users/nonfoods/new.html.erb
<div class="container">
　<h2 class="toph1" style="margin-bottom: 30px;">雑貨品アイデア新規投稿</h2>
    <div class="row">
      <div class="col-md-5">
        <!-- 新規投稿フォーム -->
        <%= form_for(@nonfood_new, url: '/users/nonfoods') do |f| %>
          <% if @nonfood.present? %>
          <%= render 'layouts/error_messages', resource: @nonfood %>
          <% end %>
          <div class="nonfoodpost__image">
            <%= f.label :nonfood_image, "雑貨品イメージ画像" %>
            <%= attachment_image_tag @nonfood_new, :nonfood_image, format: "jpeg",
             id: "img_prev", fallback: "no_image.jpg" %>
          <br>
            画像選択<%= f.attachment_field :nonfood_image %>
          </div>
          <br>
          <div><%= f.label :nonfood_name, "アイデア名（雑貨品）" %><br>
               <%= f.text_field :nonfood_name, :size=>"60" %>
          </div>
          <div>
              <%= f.label :nonfood, :タグ付け %><br>
              <%= f.text_field :tag_list, value: @nonfood_new.tag_list.join(','), :size=>"60" %>
          </div>
          <div>
             <%= f.label :nonfood_introduction, "商品説明(用途・形・お値段等)" %><br>
             <%= f.text_area :nonfood_introduction, :size=>"60x11" %>
          </div>
          <div>
             <%= f.submit('保存する',class: 'btn btn-info my-1 mb-5 px-5') %>
          </div>
        <% end %>
      </div>
    </div>
</div>

<script>
$(document).on("turbolinks:load", function(){
  function readURL(input) {
    if(input.files && input.files[0]){
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.nonfood_image').attr('src', e.target.result);　//取得したurlにアップロード画像のurlを挿入
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  // inputのidから情報の取得
  $("#nonfood_nonfood_image").change(function(){
    readURL(this);
  });
});
</script>

app/views/users/nonfoods/show.html.erb
<div class="container">
  <h2>投稿詳細</h2>
    <div class="row">
      <div class="col-md-8">
        <span class="nonfoodpost__image" style="display: block; text-align: center;">
          <%= attachment_image_tag @nonfood, :nonfood_image,　format: 'jpeg' %>
        </span>
　　　　 <p class="show1">/ アイデア名 /</p>
        <p class="show2"><%= @nonfood.nonfood_name %></p>
        <p class="show1">/ タグ /</p>
        <p class="show2"><%= @nonfood.tag_list %></p>
        <p class="show1">/ 投稿者 /</p>
        <p class="show2"><%= @nonfood.user.name %></p>
　　　　 <p class="show1">/ アイデア説明 /</p>
        <div class="show2"><%= simple_format(@nonfood.nonfood_introduction) %></div>
        <p class="show1">/ 登録日 /</p>
        <p class="show2"><%= l @nonfood.created_at, format: :short %></p>
        <div>
        <!-- 編集ボタン表示 -->
          <% if @user == current_user %>
            <%= link_to "削除",users_nonfood_path(@nonfood), method: :delete, class: "btn btn-danger pull-right", "data-confirm" => "本当に削除しますか？" %>
            <%=link_to "編集",edit_users_nonfood_path(@nonfood),method: :get, class: "btn btn-success pull-right" %>
          <% end %>
        </div><br><br>
        <div style="text-align: right; border-bottom: solid 1px #ccc; margin-bottom: 2px;" >
          <%= link_to "一覧へ", users_nonfoods_path ,class: 'btn btn-info my-1 mb-5 px-5' %>
        </div>
        <!--ここまで -->
        <% if user_signed_in? %>
          <!-- いいね表示ここから -->
          <span class="nonfood_<%= @nonfood.id %>" style="display: block; text-align: left;">
            <%= render 'nonfood', nonfood: @nonfood %>
          </span>
          <!-- ここまで -->
          <%= @nonfood_comments.count %>件コメント
          <!-- コメント表記 -->
          <table id="comments_area" class="table table-hover table-inverse">
            <%= render partial: 'users/nonfood_comments/index', locals: { nonfood_comments: @nonfood_comments } %>
          </table>
          <!-- コメントここまで -->
          <!-- コメント入力フォーム -->
          <%= render partial: 'users/nonfood_comments/form', locals: { nonfood_comment: @nonfood_comment, nonfood: @nonfood } %>
          <!-- ここまで -->
        <% end %>
      </div>
    </div>
</div>