config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
      controllers: {
        sessions: 'admins/sessions',
        passwords: 'admins/passwords',
        registrations: 'admins/registrations',
  }

	namespace :admins do
    get 'home/about'
    resources :contacts
	end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'home#top'
  post 'users/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'users/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  get "user/follow/:id" => "users/users#follow", as:'user_follow'
  get "user/followed:id" => "users/users#followed", as:'user_followed'
  get 'food_comment/new'
  get '/search' => 'search#search', as: 'search'

  namespace :users do
    get 'users/userallpost'
    get 'users/favolist'

    resources :users
    resources :contacts
  	resources :foods do
      resource :food_favorites, only: [:create, :destroy]
      resources :food_comments, only: [:create, :destroy]
    end
    resources :nonfoods do
      resource :nonfood_favorites, only: [:create, :destroy]
      resources :nonfood_comments, only: [:create, :destroy]
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :food_comments, dependent: :destroy
  has_many :food_comment_users, through: :food_comments, source: 'user'
  has_many :food_favorites, dependent: :destroy
  attachment :food_image

  validates :food_name, presence: true
  validates :food_introduction, presence: true, length: { maximum: 300 }
  acts_as_taggable

  def food_favorited_by?(user)
    food_favorites.where(user_id: user.id).exists?
  end
end

app/models/food_comment.rb
class FoodComment < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :food_comment, presence: true
end

app/models/food_favorite.rb
class FoodFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/nonfood.rb
class Nonfood < ApplicationRecord
  belongs_to :user
  has_many :nonfood_comments, dependent: :destroy
  has_many :nonfood_comment_users, through: :nonfood_comments, source: 'user'
  has_many :nonfood_favorites, dependent: :destroy

  attachment :nonfood_image
  acts_as_taggable

  validates :nonfood_name, presence: true
  validates :nonfood_introduction, presence: true, length: { maximum: 300 }

  def nonfood_favorited_by?(user)
    nonfood_favorites.where(user_id: user.id).exists?
  end
end

app/models/nonfood_comment.rb
class NonfoodComment < ApplicationRecord
  belongs_to :user
  belongs_to :nonfood
  validates :nonfood_comment, presence: true
end

app/models/nonfood_favorite.rb
class NonfoodFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :nonfood
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :foods, dependent: :destroy
  has_many :nonfoods, dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :nonfood_comments, dependent: :destroy
  has_many :food_favorites, dependent: :destroy
  has_many :nonfood_favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォロー取得 # rubocop:disable Rails/InverseOf
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy # フォロワー取得 # rubocop:disable Rails/InverseOf
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :contact, dependent: :destroy
  attachment :user_image

  enum profession: { profession_private: 0, unemployed: 1, worker: 2, housework: 3 }
  enum gender: { gender_private: 0, man: 1, human: 2 }
  enum age_group: { age_private: 0, Twenties: 1, thirties: 2, forties: 3,
                    fifties: 4, sixties: 5, seventies: 6, eighties: 7, nineties: 8 }
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      users_user_path(current_user)
    when Admin
      admins_contacts_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @user = current_user
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_to request.referer
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params['search']['model']
    @content = params['search']['content']
    @datas = search_for(@model, @content)
  end

  # 部分検索
  def search_part(model, content)
    if model == 'user' # rubocop:disable Style/CaseLikeIf
      User.where('name LIKE ?', "%#{content}%")
    elsif model == 'food'
      Food.where('food_name LIKE ?', "%#{content}%")
    elsif model == 'nonfood'
      Nonfood.where('nonfood_name LIKE ?', "%#{content}%")
    end
  end

  def search_for(model, content)
    search_part(model, content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/contacts_helper.rb
module Users::ContactsHelper
end

app/helpers/users/foods_helper.rb
module Users::FoodsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/home/top.html.erb
<body>
<!-- トップイメージ部分 -->
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
      <div class="topimage center-block" >
        <h1 style="color: white">Tunagukoe</h1>
        <h3 style="color: white">あなたの声(アイデア)を伝えてみませんか？</h3>
        <div class="sign_up">
          <h3 class="topimagelog">
            <br><%= link_to "新規登録", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up", :style=>"color:white; text-decoration: none;" %>
            　<%= link_to "ログイン", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in", :style=>"color:white; text-decoration: none;" %></h3>
        </div>
      </div>
  </div>
</div>
<!-- サイト概要　-->
  <section class="container">
    <h1 id="thisabout" class="font-weight-bold text-center ">このサイトについて</h1><br>
    <div class="row">
      <div class="col-lg-6">
          <div class="row">
              <img class="col-sm-6" src="<%= asset_path "chain.png" %>">
              <div class="col-sm-6">
                  <h3>1.あなたと商品開発者・仕入担当をつなぐサイトです。</h3>
                  <p>商品の開発・仕入れ担当者は日々生活を向上させる商品開発に取り組んでいます。</p>
              </div>
          </div>
      </div>
      <div class="col-lg-6">
        <div class="row"> <img class="col-sm-6" src="<%= asset_path "hear.jpg" %>">
            <div class="col-sm-6">
              <h3>2.企業はあなたの声を聞きたがっています。</h3>
              <p>みなさんの日常におけるさまざまなシーン・思いを参考にできたら、より具体的な開発を行えます。</p>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <div class="row"> <img class="col-sm-6" src="<%= asset_path "structure.jpg" %>">
          <div class="col-sm-6">
            <h3>3.みんなの声が形になるかもしれません。</h3>
            <p>ふとこんなアイデア思いついた！そのちょっとしたアイデアって、みんなも思ってる生活のお役立ちに貢献できるかも！</p>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="row"> <img class="col-sm-6" src="<%= asset_path "simple.jpg" %>">
          <div class="col-sm-6">
            <h3>4.シンプルなサイト構成です。</h3>
            <p>投稿した声を担当者や周りの人達が日々キャッチ、登録して発信して交流するシンプルなサイトです。</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- サイト使い方 -->
    <hr>
  <section class="container">
    <h1 class="font-weight-bold text-center ">このサイトの使い方</h1><br>
    <div class="row">
      <div class="col-lg-7 text-center ">
          <h2 class="font-weight-bold">1.さっそく登録してみよう!!</h2>
          <p class="lead" style="line-height: 2.0;">本サイトは会員登録をしない場合は閲覧のみが可能です。<br>自ら情報を発信したり他の人とやり取りするなど、<br>機能を全て使う場合は会員登録をお願いします。</p>
      </div>
      <div class="col-lg-5"> <img class="img-responsive center-block" src="<%= asset_path "sign_up.jpg" %>"></div>
    </div>
    <hr>
    <div class="row">
      <div class="col-lg-7 text-center ">
          <h2 class="font-weight-bold">2.投稿してみよう!!</h2>
          <p class="lead" style="line-height: 2.0;">会員登録後はマイページから食品のアイデア・雑貨品の<br>アイデアに分かれて新規投稿を行いましょう。<br>ふと思いついたアイデアも外歓迎です！！<br>また他の人の投稿にいいねやコメントを残して、<br>他の人とのつながりでより思いのこもったアイデアに。</p>
      </div>
      <div class="col-lg-5 order-md-1"> <img class="img-responsive center-block" src="<%= asset_path "posts.jpg" %>">
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-lg-7 text-center ">
          <h2 class="font-weight-bold">3.投稿を見よう!!</h2>
          <p class="lead" style="line-height: 2.0;">みんなの日常での色んな声（アイデア）が載っています。<br>参考にすることで日々の生活がより豊かになるかもしれません。<br>コメント機能を使って意見を出し合えば、より深いアイデアになるかもしれません。<br>
      </div>
      <div class="col-lg-5"> <img class="img-responsive center-block" src="<%= asset_path "look.jpg" %>"> </div>
    </div><br>
    <p style="border-bottom: 1px solid white;"></p>
    <div class="row">
      <div class="col-lg-7 text-center ">
          <h2 class="font-weight-bold">このサイトはポートフォリオサイトです</h2>
          <p class="lead" style="line-height: 2.0;">
            テスト動作確認可能です。<br>
            <%= link_to '管理者側', new_admin_session_path %>ログインアドレス"a@a"パスワード"aaaaaa"<br>
            <%= link_to '顧客側', new_user_session_path %>ログインアドレス"b@b"パスワード"bbbbbb"<br>
      </div>
    </div>
  </section>
</body>

app/views/search/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <% if @model == "user" %>
        <h2>顧客</h2>
        <h3>”<%= @content %>”の検索結果</h3>
          <% @datas.each do |datas| %>
            <table class="table">
              <tr>
                <td><%=link_to datas.name, users_user_path(datas) %></td>
              </tr>
            </table>
          <% end %>

      <% elsif @model == "food"%>
        <h2>食品記事</h2>
        <h3>”<%= @content %>”の検索結果</h3>
      	  <% @datas.each do |datas| %>
        	  <table class="table">
              <tr>
                <td><%=link_to datas.food_name, users_food_path(datas)%></td>
              </tr>
            </table>
          <% end %>

      <% elsif @model == "nonfood"%>
        <h2>雑貨品記事</h2>
        <h3>”<%= @content %>”の検索結果</h3>
      	  <% @datas.each do |datas| %>
        	  <table class="table">
              <tr>
                <td><%=link_to datas.nonfood_name, users_nonfood_path(datas)%></td>
              </tr>
            </table>
          <% end %>
      <% else %>
      <% end %>
    </div>
  </div>
</div>