config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
      controllers: {
        sessions: 'admins/sessions',
        passwords: 'admins/passwords',
        registrations: 'admins/registrations',
  }

	namespace :admins do
    get 'home/about'
    resources :contacts
	end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'home#top'
  post 'users/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'users/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  get "user/follow/:id" => "users/users#follow", as:'user_follow'
  get "user/followed:id" => "users/users#followed", as:'user_followed'
  get 'food_comment/new'
  get '/search' => 'search#search', as: 'search'

  namespace :users do
    get 'users/userallpost'
    get 'users/favolist'

    resources :users
    resources :contacts
  	resources :foods do
      resource :food_favorites, only: [:create, :destroy]
      resources :food_comments, only: [:create, :destroy]
    end
    resources :nonfoods do
      resource :nonfood_favorites, only: [:create, :destroy]
      resources :nonfood_comments, only: [:create, :destroy]
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :food_comments, dependent: :destroy
  has_many :food_comment_users, through: :food_comments, source: 'user'
  has_many :food_favorites, dependent: :destroy
  attachment :food_image

  validates :food_name, presence: true
  validates :food_introduction, presence: true, length: { maximum: 300 }
  acts_as_taggable

  def food_favorited_by?(user)
    food_favorites.where(user_id: user.id).exists?
  end
end

app/models/food_comment.rb
class FoodComment < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :food_comment, presence: true
end

app/models/food_favorite.rb
class FoodFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/nonfood.rb
class Nonfood < ApplicationRecord
  belongs_to :user
  has_many :nonfood_comments, dependent: :destroy
  has_many :nonfood_comment_users, through: :nonfood_comments, source: 'user'
  has_many :nonfood_favorites, dependent: :destroy

  attachment :nonfood_image
  acts_as_taggable

  validates :nonfood_name, presence: true
  validates :nonfood_introduction, presence: true, length: { maximum: 300 }

  def nonfood_favorited_by?(user)
    nonfood_favorites.where(user_id: user.id).exists?
  end
end

app/models/nonfood_comment.rb
class NonfoodComment < ApplicationRecord
  belongs_to :user
  belongs_to :nonfood
  validates :nonfood_comment, presence: true
end

app/models/nonfood_favorite.rb
class NonfoodFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :nonfood
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :foods, dependent: :destroy
  has_many :nonfoods, dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :nonfood_comments, dependent: :destroy
  has_many :food_favorites, dependent: :destroy
  has_many :nonfood_favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォロー取得 # rubocop:disable Rails/InverseOf
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy # フォロワー取得 # rubocop:disable Rails/InverseOf
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :contact, dependent: :destroy
  attachment :user_image

  enum profession: { profession_private: 0, unemployed: 1, worker: 2, housework: 3 }
  enum gender: { gender_private: 0, man: 1, human: 2 }
  enum age_group: { age_private: 0, Twenties: 1, thirties: 2, forties: 3,
                    fifties: 4, sixties: 5, seventies: 6, eighties: 7, nineties: 8 }
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      users_user_path(current_user)
    when Admin
      admins_contacts_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @user = current_user
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_to request.referer
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params['search']['model']
    @content = params['search']['content']
    @datas = search_for(@model, @content)
  end

  # 部分検索
  def search_part(model, content)
    if model == 'user' # rubocop:disable Style/CaseLikeIf
      User.where('name LIKE ?', "%#{content}%")
    elsif model == 'food'
      Food.where('food_name LIKE ?', "%#{content}%")
    elsif model == 'nonfood'
      Nonfood.where('nonfood_name LIKE ?', "%#{content}%")
    end
  end

  def search_for(model, content)
    search_part(model, content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/foods_helper.rb
module Users::FoodsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。以下ご確認お願いいたします。</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Font Awesome読み込みコード-->
　　 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
  <body>
    <div class="wrapper">
      <div class="container">
        <header class="navbar navbar-fixed-top navbar-inverse" style=" background-color: #FFA500;">
          <div class="nav navbar-nav navbar-left">
            <h2><%= link_to 'TunaguKoe', root_path, class: "header-logo", style: "color:white; padding-left:100px; font-size: 50px; text-decoration: none;" %></h2>
          </div>
          <div class="collapse navbar-collapse flex-column navbar-right" id="navbarSupportedContent" >
            <div class="site-description" style="margin-left: 45%; ">
              <%= form_tag(search_path, method: :get) do %>
                <%= text_field_tag 'search[content]' %>
                <%= select_tag 'search[model]', options_for_select({ "顧客" => "user", "食品投稿" => "food", "雑貨品投稿" => "nonfood" }) %>
                <%= submit_tag '検索', class: "btn btn-info" %>
              <% end %>
            </div>
                <nav>
                  <ul class="nav navbar-nav navbar-light navbar-center" style=" padding-right: 100px;">
                    <% if user_signed_in? %>
                        <li class="nav-item"><%= link_to "マイページ", users_user_path(current_user), class: "glyphicon glyphicon-home home", style: "color:white;" %></li>
                        <li class="nav-item"><%= link_to "食品投稿一覧", users_foods_path, class: "glyphicon glyphicon-cutlery", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "雑貨品投稿一覧", users_nonfoods_path, class: "glyphicon glyphicon-book books", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout", style: "color:white;"  %></li>
                        <li class="nav-item ">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"　>
                              さっそく投稿 <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                              <li><%= link_to "食品投稿", new_users_food_path %></li>
                              <li><%= link_to "雑貨品投稿", new_users_nonfood_path %></li>
                              <li role="separator" class="divider"></li>
                              <li><%= link_to "お問い合わせ", new_users_contact_path, class: "glyphicon glyphicon-envelope" %></li>
                            </ul>
                        </li>
                    <% elsif admin_signed_in? %>
                        <li class="nav-item"><%= link_to "このサイトについて", root_path(anchor: 'thisabout'), class: "glyphicon glyphicon-link about", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "問い合わせ一覧", admins_contacts_path, class: "glyphicon glyphicon-envelope", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout", style: "color:white;"  %></li>
                    <% else %>
                        <li class="nav-item"><%= link_to "このサイトについて", root_path(anchor: 'thisabout'), class: "glyphicon glyphicon-link about", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "食品投稿一覧", users_foods_path, class: "glyphicon glyphicon-cutlery", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "雑貨品投稿一覧", users_nonfoods_path, class: "glyphicon glyphicon-book books", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up", style: "color:white;"  %></li>
                        <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in", style: "color:white;"  %></li>
                    <% end %>
                  </ul>
                </nav>
          </div>
        </header>
      </div>
      </div><br><br><br><br>

    <%= yield %>
    <br>
    <footer class="footer" style="height:60px;">
          <p style="font-size: 24px; line-height: 30px;">© 2020 Tunagukoe</p>
    </footer>
  </body>
</html>